server {
  listen 80;
  server_name quadravise.com;

  root /var/www/quadravise/web;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  location /api/ {
    proxy_pass http://127.0.0.1:5000/api/;
  }
}
