ALTER TABLE site_settings
  ADD COLUMN IF NOT EXISTS industries_served VARCHAR(40) NOT NULL DEFAULT '6',
  ADD COLUMN IF NOT EXISTS about_years_experience VARCHAR(40) NOT NULL DEFAULT '6+',
  ADD COLUMN IF NOT EXISTS about_products_delivered VARCHAR(40) NOT NULL DEFAULT '50+',
  ADD COLUMN IF NOT EXISTS about_core_team_size VARCHAR(40) NOT NULL DEFAULT '10+',
  ADD COLUMN IF NOT EXISTS about_reliability_focus VARCHAR(40) NOT NULL DEFAULT '99.9%',
  ADD COLUMN IF NOT EXISTS quadrailearn_tracks VARCHAR(40) NOT NULL DEFAULT '12+',
  ADD COLUMN IF NOT EXISTS mvp_window VARCHAR(40) NOT NULL DEFAULT '2-4 Weeks';
