ALTER TABLE site_settings
  ADD COLUMN IF NOT EXISTS instagram VARCHAR(255) NOT NULL DEFAULT 'https://instagram.com/quadravise',
  ADD COLUMN IF NOT EXISTS facebook VARCHAR(255) NOT NULL DEFAULT 'https://facebook.com/quadravise',
  ADD COLUMN IF NOT EXISTS show_linkedin BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_email BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_instagram BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_facebook BOOLEAN NOT NULL DEFAULT TRUE;
