ALTER TABLE portfolio_projects
ADD COLUMN IF NOT EXISTS show_client_name BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS services_provided TEXT[] NOT NULL DEFAULT '{}',
ADD COLUMN IF NOT EXISTS engagement_type VARCHAR(80),
ADD COLUMN IF NOT EXISTS team_size INTEGER,
ADD COLUMN IF NOT EXISTS project_role VARCHAR(255),
ADD COLUMN IF NOT EXISTS business_problem TEXT,
ADD COLUMN IF NOT EXISTS technical_challenges TEXT,
ADD COLUMN IF NOT EXISTS project_goals TEXT,
ADD COLUMN IF NOT EXISTS solution_summary TEXT;
