ALTER TABLE portfolio_projects
ADD COLUMN IF NOT EXISTS featured_image_alt VARCHAR(255),
ADD COLUMN IF NOT EXISTS gallery_images JSONB NOT NULL DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS video_url TEXT,
ADD COLUMN IF NOT EXISTS demo_url TEXT,
ADD COLUMN IF NOT EXISTS live_url TEXT,
ADD COLUMN IF NOT EXISTS design_url TEXT,
ADD COLUMN IF NOT EXISTS document_attachments JSONB NOT NULL DEFAULT '[]'::jsonb;
